//
//  CloudKitShareAppDelegate.swift
//  filmfreaks
//
//  Routes CloudKit share invitations into the app.
//

internal import UIKit
import CloudKit
import UserNotifications

extension Notification.Name {
    static let cloudKitShareAccepted = Notification.Name("CloudKitShareAccepted")
    static let pushDeepLinkRequested = Notification.Name("PushDeepLinkRequested")
}

final class CloudKitShareAppDelegate: NSObject, UIApplicationDelegate, UNUserNotificationCenterDelegate {

    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
    ) -> Bool {
        NotificationsPermissionManager.shared.bootstrapIfNeeded(application: application, delegate: self)
        return true
    }

    // MARK: - Remote notifications (P2)

    func application(
        _ application: UIApplication,
        didReceiveRemoteNotification userInfo: [AnyHashable: Any],
        fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void
    ) {
        CloudKitRemoteNotificationDebugger.log(userInfo: userInfo)

        // P2 (light/full): Best-effort fetch + handling. Method name must match coordinator.
        Task {
            let didFetch = await CloudKitActivityPushFetchCoordinator.fetchAndLog(userInfo: userInfo)
            completionHandler(didFetch ? .newData : .noData)
        }
    }

    // MARK: Scene delegate wiring

    /// SwiftUI apps are Scene-based. CloudKit share acceptance is often delivered via the Scene delegate.
    func application(
        _ application: UIApplication,
        configurationForConnecting connectingSceneSession: UISceneSession,
        options: UIScene.ConnectionOptions
    ) -> UISceneConfiguration {
        // Preserve the scene configuration generated by SwiftUI, but add our delegate
        // so CloudKit share acceptance is delivered reliably.
        let config = connectingSceneSession.configuration
        config.delegateClass = CloudKitShareSceneDelegate.self
        return config
    }

    // MARK: Fallback (older delivery path)

    func application(
        _ application: UIApplication,
        userDidAcceptCloudKitShareWith cloudKitShareMetadata: CKShare.Metadata
    ) {
        // Some OS versions still call the app delegate path.
        Task { await CloudKitShareCoordinator.shared.accept(cloudKitShareMetadata) }
    }

    // MARK: - UNUserNotificationCenterDelegate

    func userNotificationCenter(
        _ center: UNUserNotificationCenter,
        willPresent notification: UNNotification
    ) async -> UNNotificationPresentationOptions {
        // Allow banners while app is in foreground (esp. for local notifications later).
        return [.banner, .sound]
    }

    func userNotificationCenter(
        _ center: UNUserNotificationCenter,
        didReceive response: UNNotificationResponse
    ) async {
        // Deep link when the user taps on a push.
        PushDeepLinkRouter.route(userInfo: response.notification.request.content.userInfo)
    }
}
